name: Markdown

#on: push


jobs:
  build:
    
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2


     # Setup Python
    - run: sudo apt-get install python3 python3-pip
    - run: pip install webassets jsmin
    - uses: actions/checkout@v2
    - name: Convert Markdown To HTML 
    # Run the Python Script
      run: |
         python3 .github/python.py 
         python3 .github/generate_sitemap.py
